version: '3'
services:
  front:
      build: .
      container_name: whisperFront
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - './certbot/data:/usr/share/nginx/html/letsencrypt'
          - './certbot/conf:/etc/nginx/ssl'
      networks:
          - whisperNet

  certbot:
      image: certbot/certbot:latest
      certbot: frontendCertbot
      command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt -d Whisper.webredirect.org --agree-tos --email Grambell.whisper@gmail.com
      volumes:
          - './certbot/conf:/etc/letsencrypt'
          - './certbot/data:/usr/share/nginx/html/letsencrypt'

networks:
    whisperNet: